### ISSUE TITLE
[xwiki] accessing components

### ISSUE THREAD

**Issue by gulyx** [LearnPAd/learnpad#460]
@cjdelisle I am trying to retrieve a Sigleton XWiki component (i.e. CWXwikiBridge) from another XWiki component (i.e. RecommendationWebsocketServer).

As fist, I tried with a direct injection of a private attribute (i.e [see here](https://github.com/gulyx/learnpad/blob/cw-bridgeAndWebSockets/lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/RecommendationWebsocketServer.java#L56) ) but it did worked but unfortunately I was not able to get the precise error message.

Thus as second, I tried to retrieve the component by means a ComponentManager injected in RecommendationWebsocketServer and then queried inside the method `foo`.
However, at [L64](https://github.com/gulyx/learnpad/blob/cw-bridgeAndWebSockets/lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/RecommendationWebsocketServer.java#L64), the following exception is raised.

`Can't find descriptor for the component [role = [class eu.learnpad.cw.internal.CWXwikiBridge] hint = [eu.learnpad.cw.internal.CWXwikiBridge]]`

Note that I debugged the method `foo` by building and running the whole platform, so XWiki is running with both the components are supposed to be registered and available.

Any suggestion on why I cannot retrieve/access the singleton CWXwikiBridge?

**Comment by gulyx** [comment]
@cjdelisle this is the stacktrace reported by the execution of https://github.com/gulyx/learnpad/blob/cw-bridgeAndWebSockets/lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/internal/RecommendationWebsocketServer.java#L64

`2016-05-25 15:34:23,168 [nioEventLoopGroup-3-1] ERROR .RecommendationWebsocketServer - Can't find descriptor for the component [role = [class eu.learnpad.cw.internal.CWXwikiBridge] hint = [eu.learnpad.cw.internal.CWXwikiBridge]] 
org.xwiki.component.manager.ComponentLookupException: Can't find descriptor for the component [role = [class eu.learnpad.cw.internal.CWXwikiBridge] hint = [eu.learnpad.cw.internal.CWXwikiBridge]]
        at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:401) ~[xwiki-commons-component-default-7.4.2.jar:na]
        at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:190) ~[xwiki-commons-component-default-7.4.2.jar:na]
        at org.xwiki.component.internal.multi.DelegateComponentManager.getInstance(DelegateComponentManager.java:83) ~[xwiki-commons-component-api-7.4.2.jar:na]
        at eu.learnpad.cw.internal.RecommendationWebsocketServer.foo(RecommendationWebsocketServer.java:68) ~[lp-cw-bridge-implementation-1.0-SNAPSHOT.jar:na]
        at eu.learnpad.cw.internal.RecommendationWebsocketServer$2.call(RecommendationWebsocketServer.java:194) [lp-cw-bridge-implementation-1.0-SNAPSHOT.jar:na]
        at org.xwiki.contrib.websocket.internal.NettyWebSocket.message(NettyWebSocket.java:77) [xwiki-contrib-websocket-1.7.jar:na]
        at org.xwiki.contrib.websocket.internal.NettyWebSocketService$WebSocketServerHandler.handleWebSocketFrame(NettyWebSocketService.java:364) [xwiki-contrib-websocket-1.7.jar:na]
        at org.xwiki.contrib.websocket.internal.NettyWebSocketService$WebSocketServerHandler.channelRead0(NettyWebSocketService.java:239) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [xwiki-contrib-websocket-1.7.jar:na]
        at hidden.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [xwiki-contrib-websocket-1.7.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_101]`

**Comment by gulyx** [comment]
@cjdelisle suggested that in XWIKI the resulting Role of a component **has to be** an Interface. So the solution was injecting the interface [UICWBridge](https://github.com/gulyx/learnpad/blob/cw-bridgeAndWebSockets/lp-collaborative-workspace/lp-cw-bridge/lp-cw-bridge-implementation/src/main/java/eu/learnpad/cw/UICWBridge.java) rather than its implementation in CWXwikiBridge. Of course the binding with the annotation Name (i.e. the `hint` part) was kept to the actual implementation of the class with the string "eu.learnpad.cw.internal.CWXwikiBridge"
